### ISSUE TITLE
Cannot be played, dark mode not working

### ISSUE THREAD

**Issue by ghost** [sharn25/Anime-DL-Android-Verison#2]
Most anime works, but for some (namely Avatar: The Last Airbender and Legend of Korra), there are weird error messages when trying to play. For S1 of ATLA, it says the anime cannot be found at all. With others, the episodes say, "This location [googleuser content link] cannot be played..."

Also, the dark theme isn't working for me when I select it.

**Comment by sharn25** [comment]
Try in different sources.
